#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#    Oct 06, 2023 04:37:52 PM JST  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_script = sys.argv[0]
_location = os.path.dirname(_script)

import unknown_support

_bgcolor = '#d9d9d9'  # X11 color: 'gray85'
_fgcolor = '#000000'  # X11 color: 'black'
_compcolor = 'gray40' # X11 color: #666666
_ana1color = '#c3c3c3' # Closest X11 color: 'gray76'
_ana2color = 'beige' # X11 color: #f5f5dc
_tabfg1 = 'black' 
_tabfg2 = 'black' 
_tabbg1 = 'grey75' 
_tabbg2 = 'grey89' 
_bgmode = 'light' 

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("214x649+1100+127")
        top.minsize(1, 1)
        top.maxsize(1905, 1050)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(highlightcolor="black")

        self.top = top

        self.Button1_1 = tk.Button(self.top)
        self.Button1_1.place(relx=0.0, rely=0.143, height=96, width=215)
        self.Button1_1.configure(activebackground="beige")
        self.Button1_1.configure(borderwidth="2")
        self.Button1_1.configure(compound='left')
        self.Button1_1.configure(text='''Button''')
        self.Button1 = tk.Button(self.top)
        self.Button1.place(relx=0.0, rely=0.0, height=96, width=215)
        self.Button1.configure(activebackground="beige")
        self.Button1.configure(borderwidth="2")
        self.Button1.configure(compound='left')
        self.Button1.configure(text='''Button''')
        self.Button1_1_1 = tk.Button(self.top)
        self.Button1_1_1.place(relx=0.0, rely=0.287, height=96, width=215)
        self.Button1_1_1.configure(activebackground="beige")
        self.Button1_1_1.configure(borderwidth="2")
        self.Button1_1_1.configure(compound='left')
        self.Button1_1_1.configure(text='''Button''')
        self.Button1_1_1_1 = tk.Button(self.top)
        self.Button1_1_1_1.place(relx=0.0, rely=0.428, height=96, width=105)
        self.Button1_1_1_1.configure(activebackground="beige")
        self.Button1_1_1_1.configure(borderwidth="2")
        self.Button1_1_1_1.configure(compound='left')
        self.Button1_1_1_1.configure(text='''Button''')
        self.Button1_1_1_1_2 = tk.Button(self.top)
        self.Button1_1_1_1_2.place(relx=0.514, rely=0.428, height=96, width=105)
        self.Button1_1_1_1_2.configure(activebackground="beige")
        self.Button1_1_1_1_2.configure(borderwidth="2")
        self.Button1_1_1_1_2.configure(compound='left')
        self.Button1_1_1_1_2.configure(text='''Button''')
        self.Button1_1_1_1_1_1 = tk.Button(self.top)
        self.Button1_1_1_1_1_1.place(relx=0.514, rely=0.587, height=96
                , width=105)
        self.Button1_1_1_1_1_1.configure(activebackground="beige")
        self.Button1_1_1_1_1_1.configure(borderwidth="2")
        self.Button1_1_1_1_1_1.configure(compound='left')
        self.Button1_1_1_1_1_1.configure(text='''Button''')
        self.Listbox1 = tk.Listbox(self.top)
        self.Listbox1.place(relx=0.0, rely=0.74, relheight=0.259, relwidth=1.0)
        self.Listbox1.configure(background="white")
        self.Listbox1.configure(font="TkFixedFont")
        self.Listbox1.configure(selectbackground="#c4c4c4")
        self.Button1_1_1_1_1_1_1 = tk.Button(self.top)
        self.Button1_1_1_1_1_1_1.place(relx=0.0, rely=0.586, height=96
                , width=105)
        self.Button1_1_1_1_1_1_1.configure(activebackground="beige")
        self.Button1_1_1_1_1_1_1.configure(borderwidth="2")
        self.Button1_1_1_1_1_1_1.configure(compound='left')
        self.Button1_1_1_1_1_1_1.configure(text='''Button''')

def start_up():
    unknown_support.main()

if __name__ == '__main__':
    unknown_support.main()




